#!/usr/bin/env python3
"""Execute LLM-generated read-only Cypher against Neo4j."""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

from audit_trail import LOG_DIR, TRACE_DIR, log_event, write_json, write_text
from query_executor import Neo4jConfig, QueryExecutor, QuerySpec, load_env_file


ROOT = Path(__file__).resolve().parents[1]


def configure_output_encoding() -> None:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    if hasattr(sys.stderr, "reconfigure"):
        sys.stderr.reconfigure(encoding="utf-8")


def read_json_object(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"Expected JSON object: {path}")
    return data


def parse_json_object(raw: str | None, option_name: str) -> dict[str, Any]:
    if not raw:
        return {}
    data = json.loads(raw)
    if not isinstance(data, dict):
        raise ValueError(f"{option_name} must be a JSON object.")
    return data


def normalize_spec(args: argparse.Namespace) -> dict[str, Any]:
    spec = read_json_object(args.spec_file) if args.spec_file else {}
    inline_spec = parse_json_object(args.spec_json, "--spec-json")
    spec.update(inline_spec)

    if args.question is not None:
        spec["question"] = args.question
    if args.assumption is not None:
        spec["assumption"] = args.assumption
    if args.cypher is not None:
        spec["cypher"] = args.cypher
    if args.params is not None:
        spec["params"] = parse_json_object(args.params, "--params")

    if "params" not in spec:
        spec["params"] = {}
    if not isinstance(spec["params"], dict):
        raise ValueError("spec.params must be a JSON object.")
    if not isinstance(spec.get("cypher"), str) or not spec["cypher"].strip():
        raise ValueError("A non-empty Cypher string is required via spec.cypher or --cypher.")
    return spec


def main() -> None:
    configure_output_encoding()
    load_env_file()

    parser = argparse.ArgumentParser(description="Execute an LLM-generated read-only Neo4j query.")
    parser.add_argument("--spec-file", type=Path, help="Path to a JSON query spec generated by an LLM")
    parser.add_argument("--spec-json", help="Inline JSON query spec generated by an LLM")
    parser.add_argument("--question", help="Original natural-language question for traceability")
    parser.add_argument("--assumption", help="LLM assumption used to translate the question")
    parser.add_argument("--cypher", help="Read-only Cypher generated by an LLM")
    parser.add_argument("--params", help="JSON object with Cypher parameters")
    parser.add_argument("--uri", default=os.getenv("NEO4J_URI", "bolt://127.0.0.1:7687"))
    parser.add_argument("--user", default=os.getenv("NEO4J_USER", "neo4j"))
    parser.add_argument("--password", default=os.getenv("NEO4J_PASSWORD"))
    parser.add_argument("--database", default=os.getenv("NEO4J_DATABASE"))
    parser.add_argument("--dry-run", action="store_true", help="Validate and trace the query without executing it")
    parser.add_argument("--no-trace", action="store_true", help="Do not write trace files")
    parser.add_argument("--no-log-file", action="store_true", help="Do not write stage logs to files")
    parser.add_argument("--quiet", action="store_true", help="Suppress stage logs on stderr")
    args = parser.parse_args()
    logs_enabled = not args.quiet
    stage_logs: list[str] = []

    if not any([args.spec_file, args.spec_json, args.cypher]):
        raise SystemExit("Provide --spec-file, --spec-json, or --cypher.")
    if not args.password and not args.dry_run:
        raise SystemExit("Neo4j password is required via --password or NEO4J_PASSWORD.")

    started_at = datetime.now()
    log_event("PYTHON", "Loading LLM query spec from CLI/file input.", stage_logs, logs_enabled)
    spec_dict = normalize_spec(args)
    spec = QuerySpec.from_dict(spec_dict)
    log_event("LLM_SPEC", f"question={spec.question}", stage_logs, logs_enabled)
    log_event("LLM_SPEC", f"assumption={spec.assumption}", stage_logs, logs_enabled)
    log_event("LLM_SPEC", f"cypher={spec.cypher}", stage_logs, logs_enabled)
    log_event(
        "LLM_SPEC",
        f"params={json.dumps(spec.params, ensure_ascii=False, sort_keys=True)}",
        stage_logs,
        logs_enabled,
    )

    log_event("PYTHON", "Running read-only Cypher guard.", stage_logs, logs_enabled)
    executor = QueryExecutor(
        Neo4jConfig(
            uri=args.uri,
            user=args.user,
            password=args.password,
            database=args.database or None,
        )
    )
    execution = executor.execute(spec, dry_run=args.dry_run)
    if execution.warnings:
        log_event(
            "PYTHON",
            f"guard_warnings={json.dumps(execution.warnings, ensure_ascii=False)}",
            stage_logs,
            logs_enabled,
        )
    else:
        log_event("PYTHON", "guard_warnings=[]", stage_logs, logs_enabled)

    if execution.rejected:
        log_event("PYTHON", "Execution skipped because guard rejected the Cypher.", stage_logs, logs_enabled)
    elif args.dry_run:
        log_event("PYTHON", "Execution skipped because --dry-run is enabled.", stage_logs, logs_enabled)
    elif execution.error:
        log_event("PYTHON", f"Execution failed: {execution.error}", stage_logs, logs_enabled)
    else:
        log_event("PYTHON", f"Neo4j returned row_count={execution.row_count}.", stage_logs, logs_enabled)

    result = execution.to_dict()
    result["dry_run"] = args.dry_run

    if not args.no_trace:
        timestamp = started_at.strftime("%Y%m%d_%H%M%S")
        trace = {
            "started_at": started_at.isoformat(timespec="seconds"),
            "ended_at": datetime.now().isoformat(timespec="seconds"),
            "uri": args.uri,
            "database": args.database or "(default)",
            "spec": spec.to_dict(),
            "cypher_guard": execution.guard,
            "result": result,
        }
        trace_path = TRACE_DIR / f"llm_query_trace_{timestamp}.json"
        latest_path = TRACE_DIR / "llm_query_trace_latest.json"
        write_json(trace_path, trace)
        write_json(latest_path, trace)
        log_event("PYTHON", f"Trace written to {trace_path}.", stage_logs, logs_enabled)
        result["trace_file"] = str(trace_path)
        result["latest_trace_file"] = str(latest_path)

    log_event("PYTHON", "Printing final JSON result to stdout.", stage_logs, logs_enabled)

    if not args.no_log_file:
        timestamp = started_at.strftime("%Y%m%d_%H%M%S")
        log_path = LOG_DIR / f"llm_query_log_{timestamp}.log"
        latest_log_path = LOG_DIR / "llm_query_log_latest.log"
        log_event("PYTHON", f"Log file written to {log_path}.", stage_logs, logs_enabled)
        write_text(log_path, stage_logs)
        write_text(latest_log_path, stage_logs)
        result["log_file"] = str(log_path)
        result["latest_log_file"] = str(latest_log_path)

    print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
